<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <ProjectReference Include="../../src/backend/Trelix.Server/Trelix.Server.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
