// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trelix.Server.Persistence;

#nullable disable

namespace Trelix.Server.Persistence.Migrations
{
    [DbContext(typeof(TrelixDbContext))]
    [Migration("20260920163601_InitialStorage")]
    partial class InitialStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SecurityStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Administrators", t =>
                        {
                            t.HasCheckConstraint("CK_Administrators_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.AdministratorSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdministratorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("AdministratorSessions");
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ApplicationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SecretHash")
                        .IsUnique();

                    b.ToTable("ApplicationTokens", t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationTokens_Expiry", "ExpiresAt > CreatedAt");
                        });
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ConfigFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CurrentReleaseVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DraftJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("DraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.HasIndex("Id", "CurrentReleaseVersion");

                    b.ToTable("ConfigFiles", t =>
                        {
                            t.HasCheckConstraint("CK_ConfigFiles_Draft", "(DraftJson IS NULL AND DraftRevision = 0) OR (DraftJson IS NOT NULL AND json_valid(DraftJson) AND DraftRevision > 0)");
                        });
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ProjectEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.Release", b =>
                {
                    b.Property<Guid>("ConfigFileId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DraftRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SourceVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConfigFileId", "Version");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("ConfigFileId", "SourceVersion");

                    b.ToTable("Releases", t =>
                        {
                            t.HasCheckConstraint("CK_Releases_Json", "json_valid(Json)");

                            t.HasCheckConstraint("CK_Releases_Source", "SourceVersion IS NULL OR SourceVersion < Version");

                            t.HasCheckConstraint("CK_Releases_Version", "Version > 0 AND DraftRevision > 0");
                        });
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.TokenScope", b =>
                {
                    b.Property<Guid>("ApplicationTokenId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("ApplicationTokenId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("TokenScopes");
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.AdministratorSession", b =>
                {
                    b.HasOne("Trelix.Server.Persistence.Entities.Administrator", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ConfigFile", b =>
                {
                    b.HasOne("Trelix.Server.Persistence.Entities.ProjectEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trelix.Server.Persistence.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("Id", "CurrentReleaseVersion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ProjectEnvironment", b =>
                {
                    b.HasOne("Trelix.Server.Persistence.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.Release", b =>
                {
                    b.HasOne("Trelix.Server.Persistence.Entities.ConfigFile", null)
                        .WithMany()
                        .HasForeignKey("ConfigFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trelix.Server.Persistence.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("ConfigFileId", "SourceVersion")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.TokenScope", b =>
                {
                    b.HasOne("Trelix.Server.Persistence.Entities.ApplicationToken", null)
                        .WithMany("Scopes")
                        .HasForeignKey("ApplicationTokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trelix.Server.Persistence.Entities.ProjectEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Trelix.Server.Persistence.Entities.ApplicationToken", b =>
                {
                    b.Navigation("Scopes");
                });
#pragma warning restore 612, 618
        }
    }
}
